expebase/urls.py
from django.conf.urls import url

from . import views

app_name = "expebase"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard', views.dashboard , name='dashboard'),
    url(r'^result', views.result , name = "result"),
]

myDemo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^expebase/', include('expebase.urls',namespace = "expebase") ),
]

expebase/models.py
from django.db import models
# from mongoengine import *
# from myDemo.settings import DBNAME
#
# connect(DBNAME)

# Create your models here.

# class locations(models.Model):
#   street = models.CharField(max_length = 40)
#   city = models.CharField(max_length = 30)
#   state = models.CharField(max_length = 30)
#   country = models.CharField(max_length = 30)
#   zipcode = models.CharField(max_length = 30)
#   description = models.TextField()

expebase/views.py
from django.shortcuts import render
from django.http import HttpResponse
from pymongo import MongoClient
import re
from django.template.defaultfilters import slugify

# Create your views here.

def index(request):
    return HttpResponse("Welcome visit our page")

def dashboard(request):

    # client = MongoClient("localhost", 27017)
    # client = MongoClient("mongodb://localhost:27017/")
    client = MongoClient()
    db = client["mydb"]
    coll = db["Information"]
    # document = {"street": "1225 North King Street", "city": "Wilmington", "state": "Delaware",
    #             "country": "United States"}
    # coll.insert(document)
    

    solution = {'Virtual Mailroom','Virtual Business Address','Mail & Packaging Forward'}
    location = {'Wilmington, Delaware','Marysville, California'}

    if 'solution_select' in request.POST:
        result_solution = request.POST['solution_select']
    else :
        result_solution = "Empty"
    if 'location_select' in request.POST:
        result_location = request.POST['location_select']
    else :
        result_location = "Empty"

    results = ""
    result_location_arr = result_location.split(",")
    
    if len(result_location_arr) > 1:
        city = result_location_arr[0].strip()
        state = result_location_arr[1].strip()
        be_regx = "^"+state
        regx = re.compile(be_regx)
        results = db.Information.find({"solution" : result_solution, "city" : city , "state" : regx })
        #results = db.Information.find({"state" : regx })
    formlink = "expebase/"+slugify(result_location)+"/"+slugify(result_solution)
    return render(request, 'expebase/dashboard.html',{'solution' : solution, 'location': location,'result_solution' : result_solution , 'result_location' : result_location, "results":results, "formlink" : formlink})

def result(request):
    location =  request.POST['location_select']
    solution = request.POST['solution_select']
    return render(request, "expebase/result.html",{'location': location, 'solution' : solution})

templates/expebase/dashboard.html
{% load staticfiles %}
{% load static %}
{% static "" as baseUrl %}

<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->

<html>
<head>
<title>
    ExpeBase Site
</title>

    <link href = "{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <link href = "{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href = "{% static 'css/style.css' %}" rel="stylesheet" type="text/css">


</head>
<body id = "page-top" class = "index">
    <nav id = "mainNav" class ="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class = "container">
            <div class = "navbar-header">
                <button type = "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target = "#myNavbar"
                        aria-expanded = "false" aria-controls = "navbar">
                    <span class = "icon-bar top-bar"></span>
                    <span class = "icon-bar middle-bar"></span>
                    <span class = "icon-bar bottom-bar"></span>
                </button>
                <a class = "navbar-brand logo" href = "#">ExpeBase</a>
            </div>
            <div class = "collapse navbar-collapse" id = "myNavbar">
                <ul class = "nav navbar-nav navbar-right">
                    <li class = "active">
                        <a href = "#">Home</a>
                    </li>
                    <li>
                        <a href = "#">About</a>
                    </li>
                    <li>
                        <a href = "#">Services</a>
                    </li>
                    <li>
                        <a href = "#">Blog</a>
                    </li>
                    <li>
                        <a href = "#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header>
        <div class = "container">
            <div class = "row">
                <div class = "col-sm-12">
                    <div class = "intro-text">
                        <span class = "name">ExpeBase is your network of offices for your needs</span>
                        <div class = "col-sm-10 col-sm-offset-1">
                            <div class = "row clearfix">
                                <form action="{% url 'expebase:dashboard' %}" method="post" id = "form1" name = "form1">
                                    {% csrf_token %}
                                    <div class = "col-sm-4">
                                        <div class = "form-group">
                                            <label>I Want</label>
                                            <select class="form-control" name = "solution_select" id = "solution_select">
                                                <option>Choose</option>
                                                {% for sol in solution %}
                                                    {% if sol == result_solution %}
                                                        <option selected>{{ sol }}</option>
                                                    {% else %}
                                                        <option value = "{{ sol }}">{{ sol }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class = "col-sm-4">
                                        <div class = "form-group">
                                            <label>From</label>
                                            <select class = "form-control" name = "location_select" id = "location_select">
                                                <option>Choose</option>
                                                {% for loc in location %}
                                                    {% if loc == result_location %}
                                                        <option selected>{{ loc }}</option>
                                                    {% else %}
                                                        <option value = "{{ loc }}">{{ loc }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class = "col-sm-4">
                                        <div class = "form-group">
                                            <label>Email</label>
                                            <input type = "email" class = "form-control" >
                                        </div>
                                    </div>
                                    <p class = "text-center">
                                        <button type = "submit" class = "btn btn-find">Find</button>
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class = "seprator">
        <div class = "container">
            <div class = "row clearfix">
                <div class = "col-sm-7">
                    <h2>Why do we use it?</h2>

                    {% for res in results%}
                    <span class = "pull-left what-we-do">
                        <img src="{{ baseUrl }}images/{{res.image}}">
                    </span>
                    <div>                                          
                       <p>  {{ res.description }}  </p>
                    </div>
                    
                   
                   <!--  <p>        // });
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
                        dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                        It has survived not only five centuries,
                    </p> -->
                </div>
                <div class = "col-sm-5">
                    <h2>Location</h2>
                    <div id="map" style = "height:250; width:100%"></div>
                    <p class = "address">{{ res.street}},&nbsp{{ res.city }}
                        <br>
                        {{res.state}},&nbsp{{res.country}}
                    </p> 
                     {% endfor %}
                </div>
            </div>
                {% csrf_token %}
                <p class = "btn-section">
                    <button type = "submit" class = "btn btn-launch" onclick = "alert('TypeFormLink : {{ formlink }}')">LAUNCH</button>
                </p>
        </div>
    </div>
    <div class = "gray-box seprator">
        <div class = "container text-center">
            <h2>Bonorum et Malourm</h2>
            <p>
                Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam
                voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem
                sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non
                numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem
            </p>
        </div>
    </div>
    <footer>
        <div class = "container">
            <ul class = "nav hidden-xs">
                <li class = "active">
                    <a href = "#">Home</a>
                </li>
                <li>
                    <a href = "#">About</a>
                </li>
                <li>
                    <a href = "#">Services</a>
                </li>
                <li>
                    <a href = "#">Blog</a>
                </li>
                <li>
                    <a href = "#">Contact</a>
                </li>
            </ul>
            <p class = "copyright">Copyright 2017 ExpeBase</p>
        </div>
    </footer>
    
<script src = "{% static 'js/jquery.min.js' %}" ></script>
<script src = "{% static 'js/bootstrap.min.js' %}"></script>
<script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: {lat: -34.397, lng: 150.644}
        });
        var geocoder = new google.maps.Geocoder();

        // document.getElementById('submit').addEventListener('click', function() {
          geocodeAddress(geocoder, map);
        // });
      }

      function geocodeAddress(geocoder, resultsMap) {
        var address = document.getElementById('location_select').value;
        geocoder.geocode({'address': address}, function(results, status) {
          if (status === 'OK') {
            resultsMap.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
              map: resultsMap,
              position: results[0].geometry.location
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }
    </script>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyBnHlSEclSTBn7a71JBqWaB9PffTlCmsT0&callback=initMap&sensor=true" type="text/javascript"></script>
<script src="{% static 'js/gmaps.js' %}" type="text/javascript"></script>
</body>
</html>